# Docs: <https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-dependency-updates>

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers: ["kereis"]
    assignees: ["kereis"]

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule: 
      interval: "daily"
    reviewers: ["kereis"]
    assignees: ["kereis"]

  - package-ecosystem: "docker"
    directory: "/alpine"
    schedule: 
      interval: "daily"
    reviewers: ["kereis"]
    assignees: ["kereis"]
