name: Codacy Security Scan

on:
  push:
    branches:
      - 'develop'
      - 'release/*'
      - 'master'
  pull_request:
  schedule:
    - cron: '19 9 * * 4'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      # Execute Codacy Analysis CLI and generate a SARIF output with the security issues identified during the analysis
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@562ee3e92b8e92df8b67e0a5ff8aa8e261919c08 # v4.4.7
        with:
          # Check https://github.com/codacy/codacy-analysis-cli#project-token to get your project token from your Codacy repository
          # You can also omit the token and run the tools that support default configurations
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

          # SARIF uploads for Codacy not working, see https://github.com/codacy/codacy-analysis-cli-action/issues/142
          # verbose: true
          # output: results.sarif
          # format: sarif
          # # Adjust severity of non-security issues
          # gh-code-scanning-compat: true
          # # Force 0 exit code to allow SARIF file generation
          # # This will handover control about PR rejection to the GitHub side
          # max-allowed-issues: 2147483647

      # # Upload the SARIF file generated in the previous step
      # - name: Upload SARIF results file
      #   uses: github/codeql-action/upload-sarif@76621b61decf072c1cee8dd1ce2d2a82d33c17ed # v3.29.8
      #   with:
      #     sarif_file: results.sarif
      #     category: security-scan
