name: Build Docker images (alpine)

on:
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  build-images:
    name: Build '${{ matrix.architecture }}' image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture:
          - amd64
          - arm32v7
          - arm64v8
        include:
          - architecture: amd64
            dockerfile: alpine/Dockerfile
          - architecture: arm32v7
            dockerfile: alpine/Dockerfile.armhf
          - architecture: arm64v8
            dockerfile: alpine/Dockerfile.aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Login to Docker Hub registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and publish image
        uses: ./.github/actions/docker-build-image
        with:
          dockerfile: ${{ matrix.dockerfile }}
          architecture: ${{ matrix.architecture }}

  publish-manifest:
    name: Publish multiarch manifest
    needs:
      - build-images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Login to Docker Hub registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Create and publish manifest list
        uses: ./.github/actions/docker-create-manifest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        with:
          multiarch: '["amd64", "arm32v7", "arm64v8"]'
